[build]
  publish = "client/dist"
  command = "cd client && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
