[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "vite build",
  "esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
]

[start]
cmd = "NODE_ENV=production PORT=$PORT node dist/index.js"